package tech.kayys.wayang.knowledge.exchange.journal;

public enum KnowledgeAnswerResolutionLogEntryType {
    PROPOSAL_CREATED,
    VOTE_RECORDED,
    CONSENSUS_REACHED,
    CONSENSUS_REJECTED,

    ATTESTATION_CREATED,
    CONSENSUS_ACTIVATED,
    CONSENSUS_SUPERSEDED,
    CONSENSUS_REVOKED,

    LEASE_ISSUED,
    LEASE_RENEWED,
    LEASE_EXPIRED,

    MEMBERSHIP_CHANGE_PROPOSED,
    JOINT_CONFIGURATION_ACTIVATED,
    MEMBERSHIP_TRANSITION_FINALIZED,
    MEMBERSHIP_TRANSITION_ABORTED,

    SNAPSHOT_INVALIDATED,
    DEPENDENCY_INVALIDATED
}
