<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
          <groupId>tech.kayys.wayang</groupId>
          <artifactId>wayang-framework-parent</artifactId>
          <version>0.0.1</version>
          <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>wayang-registry</artifactId>
    <version>0.0.1</version>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
    </properties>

    <dependencies>
        <!-- SdkText, SdkMaps and core client utilities -->
        <dependency>
            <groupId>tech.kayys.wayang</groupId>
            <artifactId>wayang-sdk</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <!-- WayangStandardDefinition, WayangStandardAlignment*, WayangJsonSchema* -->
        <dependency>
            <groupId>tech.kayys.wayang</groupId>
            <artifactId>wayang-gollek-sdk</artifactId>
            <version>${wayang-gollek-sdk.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>tech.kayys.alkhawarizm</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>tech.kayys.gollek</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

</project>