package tech.kayys.wayang.spi.sandbox;

public enum IsolationFeature {
    PROCESS_ISOLATION,
    FILESYSTEM_ISOLATION,
    NETWORK_ISOLATION,
    CPU_LIMITS,
    MEMORY_LIMITS,
    DISK_LIMITS,
    PROCESS_LIMITS,
    READ_ONLY_ROOT,
    CREDENTIAL_ISOLATION,
    DEVICE_ISOLATION,
    NAMESPACE_ISOLATION,
    SECCOMP,
    APPARMOR,
    SELINUX,
    CAPABILITY_DROP,
    NO_NEW_PRIVILEGES,
    PID_ISOLATION,
    IPC_ISOLATION,
    USER_ISOLATION,
    TEMPORARY_WORKSPACE
}
